var EDITOR_PASSWORD="bosteros2026";
var defaultPlayers=[
{name:"Flego",tecnica:70,pase:60,definicion:80,defensa:80,fisico:80,inteligencia:75,compromiso:85,arquero:50,photo:"",status:"confirmed"},
{name:"Gabi",tecnica:60,pase:60,definicion:70,defensa:80,fisico:65,inteligencia:65,compromiso:85,arquero:50,photo:"",status:"confirmed"},
{name:"Rodri",tecnica:80,pase:70,definicion:85,defensa:50,fisico:60,inteligencia:65,compromiso:85,arquero:50,photo:"",status:"confirmed"},
{name:"Rober",tecnica:75,pase:70,definicion:80,defensa:80,fisico:65,inteligencia:70,compromiso:85,arquero:50,photo:"",status:"confirmed"},
{name:"Cabe",tecnica:65,pase:65,definicion:75,defensa:60,fisico:55,inteligencia:60,compromiso:75,arquero:50,photo:"",status:"confirmed"},
{name:"Carlitos",tecnica:70,pase:70,definicion:70,defensa:80,fisico:85,inteligencia:65,compromiso:85,arquero:50,photo:"",status:"confirmed"},
{name:"Niko",tecnica:80,pase:65,definicion:70,defensa:60,fisico:70,inteligencia:65,compromiso:70,arquero:50,photo:"",status:"confirmed"},
{name:"Joni",tecnica:60,pase:70,definicion:80,defensa:40,fisico:55,inteligencia:75,compromiso:60,arquero:50,photo:"",status:"confirmed"},
{name:"Nico",tecnica:80,pase:65,definicion:70,defensa:60,fisico:75,inteligencia:70,compromiso:70,arquero:50,photo:"",status:"confirmed"},
{name:"Leo 🇮🇹",tecnica:75,pase:80,definicion:85,defensa:40,fisico:70,inteligencia:80,compromiso:65,arquero:50,photo:"",status:"confirmed"},
{name:"Tiziano",tecnica:70,pase:70,definicion:70,defensa:75,fisico:80,inteligencia:70,compromiso:70,arquero:50,photo:"",status:"confirmed"},
{name:"Facu",tecnica:80,pase:60,definicion:70,defensa:60,fisico:60,inteligencia:60,compromiso:60,arquero:50,photo:"",status:"confirmed"},
{name:"Cuchu",tecnica:50,pase:65,definicion:60,defensa:60,fisico:50,inteligencia:50,compromiso:70,arquero:50,photo:"",status:"confirmed"},
{name:"Dylan",tecnica:75,pase:70,definicion:70,defensa:70,fisico:75,inteligencia:70,compromiso:65,arquero:50,photo:"",status:"confirmed"}];
var state={isEditor:false,players:[],teams:{a:[],b:[]},match:{day:"Miércoles",arrival:"22:00",start:"22:30",place:"Campo de fútbol Benimàmet CF",map:"https://maps.app.goo.gl/CbSoLSd9j3njXck67",cost:5,teamAColor:"yellow",teamBColor:"blue"}};
var statConfig=[["tecnica","Técnica","#35e875"],["pase","Pase","#4ca8ff"],["definicion","Def.","#ffd43b"],["defensa","Defensa","#ff5353"],["fisico","Físico","#9c6bff"],["inteligencia","Intel.","#32d4d9"],["compromiso","Comp.","#ff5bae"]];
var colorLabel={yellow:"Boca amarilla",blue:"Boca azul",white:"Boca blanca"};
function init(){var saved=localStorage.getItem("bosteros_manager_data");if(saved){try{var p=JSON.parse(saved);state.players=p.players||defaultPlayers;state.match=p.match||state.match;state.teams=p.teams||state.teams}catch(e){state.players=defaultPlayers}}else{state.players=defaultPlayers;saveData()}bindEvents();setNextWednesdayDate();renderAll()}
function saveData(){try{localStorage.setItem("bosteros_manager_data",JSON.stringify({players:state.players,match:state.match,teams:state.teams}))}catch(e){alert("No se pudo guardar. Si subiste fotos muy grandes, probá con fotos más livianas.")}}
function bindEvents(){document.querySelectorAll(".nav-btn").forEach(function(b){b.addEventListener("click",function(){showView(b.dataset.view)})});document.getElementById("editorBtn").addEventListener("click",unlockEditor);document.getElementById("logoutEditorBtn").addEventListener("click",lockEditor);document.getElementById("openPlayerModalBtn").addEventListener("click",function(){openPlayerModal()});document.getElementById("openPlayerModalBtn2").addEventListener("click",function(){openPlayerModal()});document.getElementById("closePlayerModalBtn").addEventListener("click",closePlayerModal);document.getElementById("cancelPlayerBtn").addEventListener("click",closePlayerModal);document.getElementById("savePlayerBtn").addEventListener("click",savePlayerFromModal);document.getElementById("playerPhoto").addEventListener("change",handlePhotoInput);document.getElementById("quickGenerateBtn").addEventListener("click",generateTeams);document.getElementById("generateTeamsBtn").addEventListener("click",generateTeams);document.getElementById("saveMatchBtn").addEventListener("click",saveMatchFromForm)}
function showView(id){document.querySelectorAll(".view").forEach(function(v){v.classList.remove("active")});document.querySelectorAll(".nav-btn").forEach(function(b){b.classList.toggle("active",b.dataset.view===id)});document.getElementById(id).classList.add("active");var t={dashboard:["Dashboard","Próximo partido, convocados y resumen general."],players:["Jugadores","Base de datos, fotos y aptitudes."],match:["Partido","Convocados, horarios, cancha y camisetas."],teams:["Equipos","Formación sobre la cancha."]};document.getElementById("viewTitle").textContent=t[id][0];document.getElementById("viewSubtitle").textContent=t[id][1]}
function unlockEditor(){var pass=prompt("Contraseña de editor");if(pass===EDITOR_PASSWORD){state.isEditor=true;renderEditorMode();alert("Modo editor activado")}else alert("Contraseña incorrecta")}
function lockEditor(){state.isEditor=false;renderEditorMode()}
function renderEditorMode(){document.getElementById("editorStatus").textContent=state.isEditor?"Modo editor":"Modo visitante";document.querySelector(".editor-box small").textContent=state.isEditor?"Permisos activos":"Solo lectura";document.getElementById("editorBtn").classList.toggle("hidden",state.isEditor);document.getElementById("logoutEditorBtn").classList.toggle("hidden",!state.isEditor);document.querySelectorAll(".editor-only").forEach(function(e){e.classList.toggle("hidden",!state.isEditor)});["matchDay","matchArrival","matchStart","matchPlace","matchMap","matchCost","teamAColor","teamBColor"].forEach(function(id){document.getElementById(id).disabled=!state.isEditor});renderPlayers();renderCallList()}
function setNextWednesdayDate(){var today=new Date(),diff=3-today.getDay();if(diff<0)diff+=7;var next=new Date(today);next.setDate(today.getDate()+diff);document.getElementById("dashDate").textContent=next.toLocaleDateString("es-ES",{weekday:"long",day:"numeric",month:"long"})}
function renderAll(){renderEditorMode();renderDashboard();renderPlayers();renderCallList();renderMatchForm();renderTeams()}
function overall(p){return Math.round((p.tecnica+p.pase+p.definicion+p.defensa+p.fisico+p.inteligencia+p.compromiso)/7)}
function initials(n){return n.replace("🇮🇹","").trim().substring(0,2).toUpperCase()}
function avatar(p){return p.photo?'<div class="avatar"><img src="'+p.photo+'" alt="'+p.name+'"></div>':'<div class="avatar">'+initials(p.name)+'</div>'}
function renderDashboard(){var c=state.players.filter(function(p){return p.status==="confirmed"}).length,m=state.players.filter(function(p){return p.status==="maybe"}).length,o=state.players.filter(function(p){return p.status==="out"}).length;document.getElementById("totalPlayers").textContent=state.players.length;document.getElementById("confirmedCount").textContent=c;document.getElementById("maybeCount").textContent=m;document.getElementById("outCount").textContent=o;document.getElementById("moneyTotal").textContent=c*state.match.cost+"€";document.getElementById("moneyText").textContent=c+" jugadores confirmados · "+state.match.cost+"€ por jugador";document.getElementById("dashboardPlayers").innerHTML=state.players.map(function(p,i){return playerCardHTML(p,i,false)}).join("")}
function playerCardHTML(p,i,editable){var stats=statConfig.map(function(s){var k=s[0],l=s[1],c=s[2];return '<div class="stat-row"><span>'+l+'</span><div class="bar"><i style="--w:'+p[k]+'%;--c:'+c+'"></i></div><b>'+p[k]+'</b></div>'}).join("");var actions="";if(editable&&state.isEditor)actions='<div class="card-actions"><button onclick="editPlayer('+i+')">Editar</button><button class="delete" onclick="deletePlayer('+i+')">Borrar</button></div>';return '<article class="player-card"><div class="player-top">'+avatar(p)+'<div><h4>'+p.name+'</h4><div class="ovr">'+overall(p)+' OVR</div></div></div>'+stats+actions+'</article>'}
function renderPlayers(){document.getElementById("playersGrid").innerHTML=state.players.map(function(p,i){return playerCardHTML(p,i,true)}).join("")}
function renderCallList(){document.getElementById("callList").innerHTML=state.players.map(function(p,i){var d=state.isEditor?"":"disabled";return '<div class="call-item"><div class="call-player">'+avatar(p)+'<div><strong>'+p.name+'</strong><div class="muted">'+overall(p)+' OVR</div></div></div><select class="status-select" '+d+' onchange="changeStatus('+i+',this.value)"><option value="confirmed" '+sel(p.status,"confirmed")+'>Confirmado</option><option value="maybe" '+sel(p.status,"maybe")+'>En duda</option><option value="out" '+sel(p.status,"out")+'>No viene</option></select></div>'}).join("")}
function sel(a,b){return a===b?"selected":""}
function changeStatus(i,v){if(!state.isEditor)return;state.players[i].status=v;saveData();renderDashboard();renderCallList()}
function renderMatchForm(){document.getElementById("matchDay").value=state.match.day;document.getElementById("matchArrival").value=state.match.arrival;document.getElementById("matchStart").value=state.match.start;document.getElementById("matchPlace").value=state.match.place;document.getElementById("matchMap").value=state.match.map;document.getElementById("matchCost").value=state.match.cost;document.getElementById("teamAColor").value=state.match.teamAColor;document.getElementById("teamBColor").value=state.match.teamBColor}
function saveMatchFromForm(){if(!state.isEditor)return;state.match.day=document.getElementById("matchDay").value;state.match.arrival=document.getElementById("matchArrival").value;state.match.start=document.getElementById("matchStart").value;state.match.place=document.getElementById("matchPlace").value;state.match.map=document.getElementById("matchMap").value;state.match.cost=Number(document.getElementById("matchCost").value)||5;state.match.teamAColor=document.getElementById("teamAColor").value;state.match.teamBColor=document.getElementById("teamBColor").value;saveData();renderDashboard();renderTeams();alert("Partido guardado")}
function openPlayerModal(i){if(!state.isEditor){alert("Necesitás activar modo editor");return}document.getElementById("playerModal").classList.remove("hidden");document.getElementById("editingIndex").value="";var e={name:"",tecnica:50,pase:50,definicion:50,defensa:50,fisico:50,inteligencia:50,compromiso:50,arquero:50,photo:""};if(typeof i==="number"){document.getElementById("modalTitle").textContent="Editar jugador";document.getElementById("editingIndex").value=i;fillModal(state.players[i])}else{document.getElementById("modalTitle").textContent="Nuevo jugador";fillModal(e)}}
function fillModal(p){document.getElementById("playerName").value=p.name;["tecnica","pase","definicion","defensa","fisico","inteligencia","compromiso","arquero"].forEach(function(k){document.getElementById(k).value=p[k]||50});var pr=document.getElementById("photoPreview");pr.dataset.photo=p.photo||"";pr.innerHTML=p.photo?'<img src="'+p.photo+'">':"📷";document.getElementById("playerPhoto").value=""}
function closePlayerModal(){document.getElementById("playerModal").classList.add("hidden")}
function editPlayer(i){openPlayerModal(i)}
function deletePlayer(i){if(!state.isEditor)return;if(!confirm("¿Borrar a "+state.players[i].name+"?"))return;state.players.splice(i,1);state.teams={a:[],b:[]};saveData();renderAll()}
function handlePhotoInput(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){var img=new Image();img.onload=function(){var canvas=document.createElement("canvas"),max=420,scale=Math.min(max/img.width,max/img.height,1);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);var data=canvas.toDataURL("image/jpeg",.82),pr=document.getElementById("photoPreview");pr.dataset.photo=data;pr.innerHTML='<img src="'+data+'">'};img.src=ev.target.result};r.readAsDataURL(f)}
function savePlayerFromModal(){if(!state.isEditor)return;var name=document.getElementById("playerName").value.trim();if(!name){alert("Poné el nombre");return}var p={name:name,tecnica:num("tecnica"),pase:num("pase"),definicion:num("definicion"),defensa:num("defensa"),fisico:num("fisico"),inteligencia:num("inteligencia"),compromiso:num("compromiso"),arquero:num("arquero"),photo:document.getElementById("photoPreview").dataset.photo||"",status:"confirmed"};var e=document.getElementById("editingIndex").value;if(e!==""){p.status=state.players[Number(e)].status||"confirmed";state.players[Number(e)]=p}else state.players.push(p);saveData();closePlayerModal();renderAll()}
function num(id){var v=Number(document.getElementById(id).value)||50;return Math.max(1,Math.min(100,v))}
function generateTeams(){if(!state.isEditor){alert("Necesitás activar modo editor");return}var conf=state.players.map(function(p,i){return{p:p,i:i}}).filter(function(x){return x.p.status==="confirmed"}).sort(function(a,b){return overall(b.p)-overall(a.p)});if(conf.length<2){alert("Necesitás al menos 2 confirmados");return}var a=[],b=[];conf.forEach(function(x){var sa=a.reduce(function(s,i){return s+overall(state.players[i])},0),sb=b.reduce(function(s,i){return s+overall(state.players[i])},0);if(a.length>b.length)b.push(x.i);else if(b.length>a.length)a.push(x.i);else if(sa<=sb)a.push(x.i);else b.push(x.i)});state.teams={a:a,b:b};saveData();renderTeams();showView("teams")}
function teamAverage(arr){if(!arr.length)return 0;return Math.round(arr.reduce(function(s,i){return s+overall(state.players[i])},0)/arr.length)}
function renderTeams(){var a=state.teams.a||[],b=state.teams.b||[],aa=teamAverage(a),bb=teamAverage(b),bal=Math.max(0,100-Math.abs(aa-bb)*8);document.getElementById("teamAAvg").textContent=aa+" OVR";document.getElementById("teamBAvg").textContent=bb+" OVR";document.getElementById("balanceScore").textContent=bal+"%";var la=colorLabel[state.match.teamAColor],lb=colorLabel[state.match.teamBColor];document.getElementById("teamALabel").className="shirt-tag "+state.match.teamAColor;document.getElementById("teamBLabel").className="shirt-tag "+state.match.teamBColor;document.getElementById("teamALabel").textContent=la;document.getElementById("teamBLabel").textContent=lb;document.getElementById("teamAListTitle").textContent=la;document.getElementById("teamBListTitle").textContent=lb;renderPitch(a,b);renderTeamList("teamAList",a);renderTeamList("teamBList",b)}
function renderPitch(a,b){var pa=[[12,50],[25,24],[25,50],[25,76],[40,34],[40,66],[47,50]],pb=[[88,50],[75,24],[75,50],[75,76],[60,34],[60,66],[53,50]],html="";a.forEach(function(i,n){html+=pitchPlayerHTML(state.players[i],pa[n]||[20+n*5,50],"team-a")});b.forEach(function(i,n){html+=pitchPlayerHTML(state.players[i],pb[n]||[80-n*5,50],"team-b")});document.getElementById("pitchPlayers").innerHTML=html}
function pitchPlayerHTML(p,pos,tc){return '<div class="pitch-player '+tc+'" style="left:'+pos[0]+'%;top:'+pos[1]+'%">'+avatar(p)+'<div class="name-tag">'+p.name+'</div></div>'}
function renderTeamList(id,arr){document.getElementById(id).innerHTML=arr.map(function(i){var p=state.players[i];return '<div class="team-line"><span>'+p.name+'</span><strong>'+overall(p)+'</strong></div>'}).join("")||'<p class="muted">Todavía no hay equipo generado.</p>'}
init();
